INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 13, 88, 'Mongolian', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 13, 39, 'Mongolian', 2024, 1, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 13, 31, 'Mongolian', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 81, 88, 'Fijian', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 81, 39, 'Fijian', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 81, 31, 'Fijian', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 64, 88, 'Liechtensteiner', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 64, 39, 'Liechtensteiner', 2024, 1, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 64, 31, 'Liechtensteiner', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 7, 88, 'Croatian', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 7, 39, 'Croatian', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 7, 31, 'Croatian', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (58, 24, 88, 'Uruguayan', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (58, 24, 39, 'Uruguayan', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (58, 24, 31, 'Uruguayan', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (34, 8, 88, 'Guatemalan', 2024, 1, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (34, 8, 39, 'Guatemalan', 2024, 1, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (34, 8, 31, 'Guatemalan', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 7, 88, 'Finnish', 2024, 1, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 7, 39, 'Finnish', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 7, 31, 'Finnish', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 92, 88, 'Turkish', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 92, 39, 'Turkish', 2024, 1, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 92, 31, 'Turkish', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 88, 'Egyptian', 2024, 1, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 39, 'Egyptian', 2024, 1, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 31, 'Egyptian', 2024, 1, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 16, 88, 'Icelandic', 2024, 1, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 16, 39, 'Icelandic', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 16, 31, 'Icelandic', 2024, 1, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 58, 18, 'Indian', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 58, 71, 'Indian', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 58, 78, 'Indian', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 36, 18, 'Vanuatuan', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 36, 71, 'Vanuatuan', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 36, 78, 'Vanuatuan', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 13, 18, 'Bangladeshi', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 13, 71, 'Bangladeshi', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 13, 78, 'Bangladeshi', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 55, 18, 'Monégasque', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 55, 71, 'Monégasque', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 55, 78, 'Monégasque', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 92, 18, 'Marshall Islander', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 92, 71, 'Marshall Islander', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 92, 78, 'Marshall Islander', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 68, 18, 'South Korean', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 68, 71, 'South Korean', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 68, 78, 'South Korean', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 87, 18, 'Finnish', 2024, 2, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 87, 71, 'Finnish', 2024, 2, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 87, 78, 'Finnish', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 46, 18, 'Saint Kitts and Nevis', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 46, 71, 'Saint Kitts and Nevis', 2024, 2, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 46, 78, 'Saint Kitts and Nevis', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 93, 18, 'British', 2024, 2, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 93, 71, 'British', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 93, 78, 'British', 2024, 2, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (44, 30, 18, 'Hungarian', 2024, 2, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (44, 30, 71, 'Hungarian', 2024, 2, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (44, 30, 78, 'Hungarian', 2024, 2, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (94, 69, 58, 'Moroccan', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (94, 69, 29, 'Moroccan', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (94, 69, 21, 'Moroccan', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (80, 52, 58, 'Namibian', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (80, 52, 29, 'Namibian', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (80, 52, 21, 'Namibian', 2024, 3, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 38, 58, 'Azerbaijani', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 38, 29, 'Azerbaijani', 2024, 3, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 38, 21, 'Azerbaijani', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (9, 34, 58, 'Belgian', 2024, 3, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (9, 34, 29, 'Belgian', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (9, 34, 21, 'Belgian', 2024, 3, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 71, 58, 'Paraguayan', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 71, 29, 'Paraguayan', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 71, 21, 'Paraguayan', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 97, 58, 'Burmese', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 97, 29, 'Burmese', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 97, 21, 'Burmese', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 20, 58, 'Cypriot', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 20, 29, 'Cypriot', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 20, 21, 'Cypriot', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (41, 27, 58, 'Malagasy', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (41, 27, 29, 'Malagasy', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (41, 27, 21, 'Malagasy', 2024, 3, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 96, 58, 'Fijian', 2024, 3, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 96, 29, 'Fijian', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (59, 96, 21, 'Fijian', 2024, 3, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (71, 40, 58, 'Hungarian', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (71, 40, 29, 'Hungarian', 2024, 3, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (71, 40, 21, 'Hungarian', 2024, 3, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (38, 11, 87, 'Colombian', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (38, 11, 17, 'Colombian', 2024, 4, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (38, 11, 97, 'Colombian', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 10, 87, 'Paraguayan', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 10, 17, 'Paraguayan', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (87, 10, 97, 'Paraguayan', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 82, 87, 'Armenian', 2024, 4, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 82, 17, 'Armenian', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (52, 82, 97, 'Armenian', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 45, 87, 'Jamaican', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 45, 17, 'Jamaican', 2024, 4, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (47, 45, 97, 'Jamaican', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 66, 87, 'Bangladeshi', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 66, 17, 'Bangladeshi', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 66, 97, 'Bangladeshi', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 31, 87, 'Guatemalan', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 31, 17, 'Guatemalan', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (79, 31, 97, 'Guatemalan', 2024, 4, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (78, 8, 87, 'Greek', 2024, 4, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (78, 8, 17, 'Greek', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (78, 8, 97, 'Greek', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 95, 87, 'Irish', 2024, 4, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 95, 17, 'Irish', 2024, 4, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 95, 97, 'Irish', 2024, 4, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 10, 87, 'Azerbaijani', 2024, 4, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 10, 17, 'Azerbaijani', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (70, 10, 97, 'Azerbaijani', 2024, 4, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (89, 77, 87, 'Cypriot', 2024, 4, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (89, 77, 17, 'Cypriot', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (89, 77, 97, 'Cypriot', 2024, 4, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 9, 20, 'Bahraini', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 9, 37, 'Bahraini', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (10, 9, 73, 'Bahraini', 2024, 5, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (32, 81, 20, 'Peruvian', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (32, 81, 37, 'Peruvian', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (32, 81, 73, 'Peruvian', 2024, 5, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (2, 50, 20, 'Moroccan', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (2, 50, 37, 'Moroccan', 2024, 5, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (2, 50, 73, 'Moroccan', 2024, 5, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 16, 20, 'Swedish', 2024, 5, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 16, 37, 'Swedish', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (1, 16, 73, 'Swedish', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 72, 20, 'Vanuatuan', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 72, 37, 'Vanuatuan', 2024, 5, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (68, 72, 73, 'Vanuatuan', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (60, 1, 20, 'Burmese', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (60, 1, 37, 'Burmese', 2024, 5, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (60, 1, 73, 'Burmese', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (86, 14, 20, 'Japanese', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (86, 14, 37, 'Japanese', 2024, 5, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (86, 14, 73, 'Japanese', 2024, 5, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 16, 20, 'Guatemalan', 2024, 5, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 16, 37, 'Guatemalan', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 16, 73, 'Guatemalan', 2024, 5, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 54, 20, 'Spanish', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 54, 37, 'Spanish', 2024, 5, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (26, 54, 73, 'Spanish', 2024, 5, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 53, 20, 'Algerian', 2024, 5, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 53, 37, 'Algerian', 2024, 5, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 53, 73, 'Algerian', 2024, 5, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (23, 33, 60, 'Grenadian', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (23, 33, 8, 'Grenadian', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (23, 33, 63, 'Grenadian', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 20, 60, 'Colombian', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 20, 8, 'Colombian', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 20, 63, 'Colombian', 2024, 6, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 56, 60, 'Iraqi', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 56, 8, 'Iraqi', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 56, 63, 'Iraqi', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (73, 42, 60, 'Mexican', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (73, 42, 8, 'Mexican', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (73, 42, 63, 'Mexican', 2024, 6, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (25, 29, 60, 'South Korean', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (25, 29, 8, 'South Korean', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (25, 29, 63, 'South Korean', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (30, 88, 60, 'Bangladeshi', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (30, 88, 8, 'Bangladeshi', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (30, 88, 63, 'Bangladeshi', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 47, 60, 'Solomon Islander', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 47, 8, 'Solomon Islander', 2024, 6, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 47, 63, 'Solomon Islander', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 62, 60, 'Tuvaluan', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 62, 8, 'Tuvaluan', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (21, 62, 63, 'Tuvaluan', 2024, 6, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 49, 60, 'Marshall Islander', 2024, 6, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 49, 8, 'Marshall Islander', 2024, 6, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 49, 63, 'Marshall Islander', 2024, 6, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 92, 60, 'Italian', 2024, 6, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 92, 8, 'Italian', 2024, 6, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 92, 63, 'Italian', 2024, 6, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (100, 78, 76, 'Georgian', 2024, 7, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (100, 78, 49, 'Georgian', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (100, 78, 8, 'Georgian', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 30, 76, 'Icelandic', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 30, 49, 'Icelandic', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 30, 8, 'Icelandic', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 11, 76, 'Palauan', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 11, 49, 'Palauan', 2024, 7, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 11, 8, 'Palauan', 2024, 7, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 86, 76, 'Dutch', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 86, 49, 'Dutch', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (50, 86, 8, 'Dutch', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (48, 70, 76, 'Solomon Islander', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (48, 70, 49, 'Solomon Islander', 2024, 7, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (48, 70, 8, 'Solomon Islander', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 76, 'Spanish', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 49, 'Spanish', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (69, 78, 8, 'Spanish', 2024, 7, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 80, 76, 'Nigerian', 2024, 7, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 80, 49, 'Nigerian', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (64, 80, 8, 'Nigerian', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 13, 76, 'American', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 13, 49, 'American', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 13, 8, 'American', 2024, 7, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (22, 15, 76, 'German', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (22, 15, 49, 'German', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (22, 15, 8, 'German', 2024, 7, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 45, 76, 'Algerian', 2024, 7, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 45, 49, 'Algerian', 2024, 7, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (42, 45, 8, 'Algerian', 2024, 7, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (36, 89, 15, 'Lebanese', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (36, 89, 78, 'Lebanese', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (36, 89, 75, 'Lebanese', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (66, 4, 15, 'Namibian', 2024, 8, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (66, 4, 78, 'Namibian', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (66, 4, 75, 'Namibian', 2024, 8, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 85, 15, 'Czech', 2024, 8, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 85, 78, 'Czech', 2024, 8, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 85, 75, 'Czech', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (45, 32, 15, 'Mauritian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (45, 32, 78, 'Mauritian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (45, 32, 75, 'Mauritian', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 89, 15, 'Mongolian', 2024, 8, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 89, 78, 'Mongolian', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (88, 89, 75, 'Mongolian', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (11, 94, 15, 'Kenyan', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (11, 94, 78, 'Kenyan', 2024, 8, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (11, 94, 75, 'Kenyan', 2024, 8, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 59, 15, 'Ecuadorian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 59, 78, 'Ecuadorian', 2024, 8, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (13, 59, 75, 'Ecuadorian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 52, 15, 'Vanuatuan', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 52, 78, 'Vanuatuan', 2024, 8, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (85, 52, 75, 'Vanuatuan', 2024, 8, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (63, 95, 15, 'Austrian', 2024, 8, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (63, 95, 78, 'Austrian', 2024, 8, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (63, 95, 75, 'Austrian', 2024, 8, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 74, 15, 'El Salvadorian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 74, 78, 'El Salvadorian', 2024, 8, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 74, 75, 'El Salvadorian', 2024, 8, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (99, 29, 94, 'Norwegian', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (99, 29, 23, 'Norwegian', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (99, 29, 96, 'Norwegian', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 27, 94, 'Burmese', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 27, 23, 'Burmese', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 27, 96, 'Burmese', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (74, 34, 94, 'Cypriot', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (74, 34, 23, 'Cypriot', 2024, 9, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (74, 34, 96, 'Cypriot', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 18, 94, 'Barbadian', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 18, 23, 'Barbadian', 2024, 9, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (31, 18, 96, 'Barbadian', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 75, 94, 'Austrian', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 75, 23, 'Austrian', 2024, 9, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (7, 75, 96, 'Austrian', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 60, 94, 'Hungarian', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 60, 23, 'Hungarian', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (72, 60, 96, 'Hungarian', 2024, 9, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 83, 94, 'German', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 83, 23, 'German', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 83, 96, 'German', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 43, 94, 'Guatemalan', 2024, 9, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 43, 23, 'Guatemalan', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (90, 43, 96, 'Guatemalan', 2024, 9, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (95, 62, 94, 'Greek', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (95, 62, 23, 'Greek', 2024, 9, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (95, 62, 96, 'Greek', 2024, 9, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (6, 41, 94, 'Honduran', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (6, 41, 23, 'Honduran', 2024, 9, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (6, 41, 96, 'Honduran', 2024, 9, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 57, 34, 'French', 2024, 10, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 57, 49, 'French', 2024, 10, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 57, 40, 'French', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 64, 34, 'Hungarian', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 64, 49, 'Hungarian', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (20, 64, 40, 'Hungarian', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 6, 34, 'Portuguese', 2024, 10, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 6, 49, 'Portuguese', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (96, 6, 40, 'Portuguese', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 96, 34, 'Ghanaian', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 96, 49, 'Ghanaian', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (92, 96, 40, 'Ghanaian', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (4, 3, 34, 'Panamanian', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (4, 3, 49, 'Panamanian', 2024, 10, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (4, 3, 40, 'Panamanian', 2024, 10, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 19, 34, 'Spanish', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 19, 49, 'Spanish', 2024, 10, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (84, 19, 40, 'Spanish', 2024, 10, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 45, 34, 'Ukrainian', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 45, 49, 'Ukrainian', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (67, 45, 40, 'Ukrainian', 2024, 10, 4); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 98, 34, 'Paraguayan', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 98, 49, 'Paraguayan', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (55, 98, 40, 'Paraguayan', 2024, 10, 2); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 80, 34, 'American', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 80, 49, 'American', 2024, 10, 3); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (33, 80, 40, 'American', 2024, 10, 5); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (98, 72, 34, 'South Korean', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (98, 72, 49, 'South Korean', 2024, 10, 1); 
INSERT INTO episode_selection (recipe_id, cook_id, judge_id, cuisine_name, episode_year, episode_number, score) VALUES (98, 72, 40, 'South Korean', 2024, 10, 1); 
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 1, 7, 'https://picsum.photos/494/950', 'By word image grow available very.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 2, 87, 'https://picsum.photos/930/461', 'Back experience down artist can clearly.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 3, 40, 'https://picsum.photos/157/788', 'Admit address investment sit Republican would nor.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 4, 10, 'https://picsum.photos/349/668', 'Talk save support sing share. Model ago think send here figure.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 5, 16, 'https://picsum.photos/154/364', 'Need back girl land seem.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 6, 88, 'https://picsum.photos/543/410', 'First sometimes off outside.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 7, 78, 'https://picsum.photos/235/676', 'Your safe station.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 8, 89, 'https://picsum.photos/777/400', 'Kitchen can later form. Account pick feeling word.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 9, 29, 'https://picsum.photos/453/765', 'Pay base enough walk course oil.');
INSERT INTO episode (episode_year, episode_number, winner_id, episode_image, episode_image_desc) VALUES (2024, 10, 3, 'https://picsum.photos/712/734', 'Someone participant standard.');
